[package]
name = "relaygate-gateway-routing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
metrics.workspace = true
relaygate-protocol.workspace = true
relaygate-route-table.workspace = true
relaygate-route-table-transport.workspace = true
relaygate-transport.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
metrics-util.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[lints]
workspace = true
