version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - containedctx
    - contextcheck
    - errorlint
    - gocritic
    - gosec
    - govet
    - ineffassign
    - nilerr
    - noctx
    - staticcheck
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - containedctx
          - contextcheck
          - errorlint
          - gosec
          - noctx
        path: _test\.go

formatters:
  exclusions:
    generated: lax
