apiVersion: v1
kind: Service
metadata:
  name: {{ include "relaygate.gatewayServiceName" . }}
  labels:
    {{- include "relaygate.labels" (dict "root" . "component" "gateway") | nindent 4 }}
  {{- with .Values.gateway.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "relaygate.selectorLabels" (dict "root" . "component" "gateway") | nindent 4 }}
  ports:
    - name: sdk
      port: {{ .Values.gateway.service.port }}
      targetPort: sdk
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "relaygate.gatewayPeerServiceName" . }}
  labels:
    {{- include "relaygate.labels" (dict "root" . "component" "gateway") | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "relaygate.selectorLabels" (dict "root" . "component" "gateway") | nindent 4 }}
  ports:
    - name: peer
      port: {{ .Values.gateway.peerPort }}
      targetPort: peer
      protocol: TCP
