{{- include "relaygate.validateValues" . }}
{{- if and (eq .Values.tls.internal.mode "mtls") (eq .Values.tls.internal.source "certManager") }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "relaygate.internalGatewayCertificateSecretName" . | quote }}
  labels:
    {{- include "relaygate.labels" (dict "root" . "component" "gateway") | nindent 4 }}
spec:
  secretName: {{ include "relaygate.internalGatewayCertificateSecretName" . | quote }}
  dnsNames:
    - {{ .Values.tls.internal.gatewayServerName | quote }}
  usages:
    - digital signature
    - server auth
    - client auth
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: {{ .Values.tls.internal.certManager.issuerRef.name | quote }}
    kind: {{ .Values.tls.internal.certManager.issuerRef.kind | quote }}
    group: {{ .Values.tls.internal.certManager.issuerRef.group | quote }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "relaygate.internalRouteTableCertificateSecretName" . | quote }}
  labels:
    {{- include "relaygate.labels" (dict "root" . "component" "route-table") | nindent 4 }}
spec:
  secretName: {{ include "relaygate.internalRouteTableCertificateSecretName" . | quote }}
  dnsNames:
    - {{ .Values.tls.internal.routeTableServerName | quote }}
  usages:
    - digital signature
    - server auth
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: {{ .Values.tls.internal.certManager.issuerRef.name | quote }}
    kind: {{ .Values.tls.internal.certManager.issuerRef.kind | quote }}
    group: {{ .Values.tls.internal.certManager.issuerRef.group | quote }}
{{- end }}
